apps/app_example/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('index_1', index_1.as_view(), name='index'), # CBV
    path('objects', ObjectsView.as_view(), name='objects'), # CBV
    path('detail_object/<pk>', ObjectDetailView.as_view(), name='detail_object'), # CBV
    path('create_object', ObjectCreateView.as_view(), name='create_object'), # CBV
    path('edit_object/<pk>', ObjectUpdateView.as_view(), name='edit_object'), # CBV
    path('delete_object/<pk>', ObjectDeleteView.as_view(), name='delete_object'), # CBV
    path('index_2', index_2, name='index_2'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static # media

from .api import api_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_example/', include('app_example.urls')),
    path('stock/', include('stock_prices.urls')),
]
urlpatterns += api_urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media

apps/app_example/models.py
# from djongo import models
from django.db import models

from django.contrib.auth.models import User

class Genre(models.Model):
    created_at = models.DateField(auto_now_add=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{ self.name }'

class Book(models.Model):
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    title = models.CharField(max_length=50)
    genre = models.ManyToManyField(Genre, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{ self.title }'

apps/app_example/forms.py
from django import forms
from .models import Book

class BookForms(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BookForms, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Book
        labels = {
            'title': 'Title',
            'genre': 'Genre',
            'author': 'Author',
        }
        fields = list(labels.keys())

    def clean(self):
        return self.cleaned_data

apps/app_example/views/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView, ListView,
    DetailView, UpdateView,
    CreateView, DeleteView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from app_example.models import Book
from app_example.forms import BookForms

class index_1(TemplateView):
    '''Class based view (just example)'''
    template_name = 'app_example/index.html'

    def get_context_data(self, **kwargs):
        context = super(index_1, self).get_context_data(**kwargs)
        context['page_title'] = 'Welcome'
        return context


class ObjectDetailView(DetailView):
    model = Book
    template_name = 'app_example/detail_object.html'

    def get_context_data(self, **kwargs):
        context = super(ObjectDetailView, self).get_context_data(**kwargs)
        context['page_title'] = 'Object Detail'
        return context


class ObjectsView(ListView):
    model = Book
    template_name = 'app_example/list_objects.html'

    def get_queryset(self):
        queryset = super(ObjectsView, self).get_queryset()
        queryset = queryset.filter(id__gte=2) # show only id > 2
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ObjectsView, self).get_context_data(**kwargs)
        context['page_title'] = 'Objects'
        ## a test to send message in any view
        # context['messages'] = [
        #     {
        #         'text': 'This is just some data',
        #         'tags': 'success',
        #     },
        # ]
        return context


class ObjectCreateView(SuccessMessageMixin, CreateView):
    model = Book
    # fields = ['title', 'genre', 'author']
    form_class = BookForms
    template_name = 'app_example/create_object.html'
    success_url = 'objects'
    success_message = 'Object created with success'

    def get_context_data(self, **kwargs):
        context = super(ObjectCreateView, self).get_context_data(**kwargs)
        context['page_title'] = 'Create Object'
        return context


class ObjectUpdateView(SuccessMessageMixin, UpdateView):
    model = Book
    template_name = 'app_example/create_object.html'
    form_class = BookForms
    success_url = reverse_lazy('objects')
    success_message = 'Object updated with success'

    def get_context_data(self, **kwargs):
        context = super(ObjectUpdateView, self).get_context_data(**kwargs)
        context['page_title'] = 'Update Object'
        return context


class ObjectDeleteView(SuccessMessageMixin, DeleteView):
    model = Book
    template_name = 'app_example/delete_object.html'
    success_url = reverse_lazy('objects')
    success_message = 'Object deleted with success'

    def delete(self, request, *args, **kwargs):
        messages.error(self.request, self.success_message)
        return super(ObjectDeleteView, self).delete(request, *args, **kwargs)


def index_2(request):
    '''Function based view'''
    context = {
        'page_title': 'Welcome'
    }
    return render(request, 'app_example/index.html', context)

apps/app_example/views/views_api.py
from django.utils.translation import gettext_lazy as _
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page


from rest_framework import viewsets
from rest_framework.response import Response

from app_example.models import Book
from app_example.serializers import BookSerializer


class BooksViewSet(viewsets.ModelViewSet):
    '''API endpoint that allows Book to be viewed or edited.'''
    authentication_classes = []
    queryset = Book.objects.all()
    serializer_class = BookSerializer

    @method_decorator(cache_page(60))
    def dispatch(self, *args, **kwargs):
        return super(BooksViewSet, self).dispatch(*args, **kwargs)

templates/app_example/create_object.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    {% include '../partials/__navbar.html' %}
    <main class="container my-5">
        <div class="starter-template text-left py-5 px-3">

            <div class="px-3 py-1 mx-auto text-left">
                <h1 class="display-4">{{ page_title }}</h1>
                <form method="post">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="col-sm-6 mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% comment %} <input
                                name="{{ field.name }}"
                                class="form-control"
                                id="{{ field.id_for_label }}"
                                {% if field.value %}
                                    value="{{ field.value }}"
                                {% endif %}
                            > {% endcomment %}
                        </div>
                    {% endfor %}

                    <input type="submit" class="btn btn-lg btn-primary" value="Submit">
                </form>
            </div>

        </div>
    </main>
{% endblock content %}

templates/app_example/delete_object.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    {% include '../partials/__navbar.html' %}
    <main class="container my-5">
        <div class="starter-template text-left py-5 px-3">

            <div class="px-3 py-1 mx-auto text-left">
                <h1 class="display-4">{{ page_title }}</h1>
                <form method="post">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{ object }}"?</p>
                    <input type="submit" class="btn btn-lg btn-danger" value="Confirm">
                    <a class="btn btn-lg btn-primary" href="{% url 'edit_object' pk=object.id %}">Go back</a>
                </form>
            </div>

        </div>
    </main>
{% endblock content %}

templates/app_example/detail_object.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    {% include '../partials/__navbar.html' %}
    <main class="container my-5">
        <div class="starter-template text-left py-5 px-3">

            <div class="px-3 py-1 mx-auto text-left">
                <h1 class="display-4">{{ object.title }}</h1>
                <p class="lead">ID: {{ object.id }}</p>
                <p class="lead">Registered at: {{ object.created_at }}</p>
                <p class="lead">Author: {{ object.author }}</p>
            </div>
            <a class="btn btn-lg btn-primary" href="{% url 'edit_object' pk=object.id %}">Edit</a>
            <a class="btn btn-lg btn-danger" href="{% url 'delete_object' pk=object.id %}">Delete</a>

        </div>
    </main>
{% endblock content %}

templates/app_example/index.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} Welcome {% endblock page_title %}

{% block other_links %}
    <link rel="shortcut icon" href="{% static 'images/django.svg' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/pages/signin.css' %}">
{% endblock other_links %}

{% block content %}

    <main class="text-center form-signin">
        <form>
            <img class="mb-4" src="{% static 'images/django.svg' %}" alt="" width="72" height="57">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
            <label for="inputEmail" class="visually-hidden">Email address</label>
            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
            <label for="inputPassword" class="visually-hidden">Password</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
            <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            <p class="mt-5 mb-3 text-muted">© 2017 – {% now "Y" %}</p>
        </form>
    </main>

{% endblock content %}

templates/app_example/list_objects.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    {% include '../partials/__navbar.html' %}
    <main class="container my-5">
        <div class="starter-template text-center py-5 px-3">
            {% include '../partials/__messages.html' %}

            <div class="px-3 py-1 mx-auto text-center">
                <h1 class="display-4">Objects</h1>
                <p class="lead">Listing registered objects.</p>
            </div>

            <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
                {% for book in book_list %}
                    <div class="col">
                        <div class="card mb-4 shadow-sm">
                            <div class="card-header">
                                <h4 class="my-0 fw-normal">Book {{ book.id }}</h4>
                            </div>
                            <div class="card-body">
                                <h1 class="card-title">{{ book.title }}</h1>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li>{{ book.author }}</li>
                                    <li>{{ book.created_at|date:'d/m/y' }}</li>
                                </ul>
                                <a href="{% url 'detail_object' pk=book.id %}" class="w-100 btn btn-lg btn-primary">See info</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </main>
{% endblock content %}